package config

// Defaults returns the built-in configuration defaults.
func Defaults() Config {
	return Config{
		Server: ServerConfig{
			Host: "127.0.0.1",
			Port: 8080,
		},
		VectorBackend:     "sqlite",
		EntityFactBackend: "sqlite",
		DefaultTenantID:   "",
		ImportanceScorer:  "heuristic",
		Postprocess: PostprocessConfig{
			Enabled:        true,
			PollIntervalMS: 250,
			BatchSize:      32,
			WorkerCount:    2,
			LeaseMS:        30000,
			MaxAttempts:    5,
			RetryBaseMS:    500,
			RetryMaxMS:     60000,
		},
		StructuredMemory: StructuredMemoryConfig{
			Enabled:               false,
			DualWriteObservations: false,
			DualWriteEvents:       false,
			MaxObservations:       3,
		},
		Retrieval: RetrievalConfig{
			AnswerTypeRoutingEnabled:             true,
			EarlyRankRerankEnabled:               true,
			TemporalResolverEnabled:              true,
			OpenDomainAlternativeResolverEnabled: false,
			Scoring: RetrievalScoringConfig{
				Algorithm: "wal",
				WAL: ScoringWeightsConfig{
					Recency:    0.1,
					Relevance:  0.8,
					Importance: 0.1,
				},
				Match: MatchScoringWeightsConfig{
					Recency:      0.05,
					Relevance:    0.70,
					Importance:   0.10,
					QueryOverlap: 0.10,
					Routing:      0.05,
				},
			},
			Search: RetrievalSearchConfig{
				AdaptiveQueryExpansionEnabled:        false,
				AdaptiveQueryMaxExtraQueries:         2,
				AdaptiveQueryWeakLexicalThreshold:    0.62,
				AdaptiveQueryPlanConfidenceThreshold: 0,
				CandidateWindowMultiplier:            5,
				CandidateWindowMin:                   50,
				CandidateWindowMax:                   200,
				CandidateWindowTemporalBoost:         40,
				CandidateWindowMultiHopBoost:         80,
				CandidateWindowFilterBoost:           30,
				EarlyRerankBaseWindow:                25,
				EarlyRerankMaxWindow:                 25,
			},
			MultiHop: RetrievalMultiHopConfig{
				EntityFactBridgeEnabled:    true,
				LLMDecompositionEnabled:    false,
				DecompositionProvider:      "openrouter",
				OpenRouterModel:            "openai/gpt-oss-120b:nitro",
				OllamaBaseURL:              "http://127.0.0.1:11434",
				OllamaModel:                "deepseek-r1:7b",
				OllamaTimeoutMS:            2000,
				MaxDecompositionQueries:    3,
				EnablePairwiseRerank:       true,
				TokenExpansionFallback:     true,
				GraphPathEnabled:           false,
				GraphMaxHops:               2,
				GraphSeedLimit:             12,
				GraphPathLimit:             128,
				GraphMinScore:              0.12,
				GraphWeight:                0.25,
				GraphTemporalValidity:      false,
				GraphSingletonInvalidation: true,
			},
		},
		Parser: ParserConfig{
			Enabled:                    false,
			Provider:                   "heuristic",
			OllamaBaseURL:              "http://127.0.0.1:11434",
			OllamaModel:                "deepseek-r1:7b",
			OpenRouterModel:            "openai/gpt-oss-120b:nitro",
			OllamaTimeoutMS:            20000,
			StoreRawTurn:               true,
			MaxFacts:                   4,
			DedupeThreshold:            0.88,
			UpdateThreshold:            0.94,
			AnswerSpanRetentionEnabled: false,
		},
		ProfileLayer: ProfileLayerConfig{
			SupportLinksEnabled: false,
		},
		Database: Database{
			SQLiteDSN: "file:pali.db?cache=shared",
		},
		Qdrant: QdrantConfig{
			BaseURL:    "http://127.0.0.1:6333",
			APIKey:     "",
			Collection: "pali_memories",
			TimeoutMS:  2000,
		},
		PGVector: PGVectorConfig{
			DSN:          "",
			Table:        "pali_memories",
			AutoMigrate:  true,
			MaxOpenConns: 10,
			MaxIdleConns: 5,
		},
		Neo4j: Neo4jConfig{
			URI:       "bolt://127.0.0.1:7687",
			Username:  "neo4j",
			Password:  "",
			Database:  "neo4j",
			TimeoutMS: 2000,
			BatchSize: 256,
		},
		Embedding: Embedding{
			Provider:             "lexical",
			FallbackProvider:     "lexical",
			ModelPath:            "./models/all-MiniLM-L6-v2/model.onnx",
			TokenizerPath:        "./models/all-MiniLM-L6-v2/tokenizer.json",
			OllamaBaseURL:        "http://127.0.0.1:11434",
			OllamaModel:          "mxbai-embed-large",
			OllamaTimeoutSeconds: 10,
		},
		OpenRouter: OpenRouterConfig{
			BaseURL:        "https://openrouter.ai/api/v1",
			APIKey:         "",
			EmbeddingModel: "openai/text-embedding-3-small:nitro",
			ScoringModel:   "openai/gpt-oss-120b:nitro",
			TimeoutMS:      10000,
		},
		Ollama: OllamaConfig{
			BaseURL:   "http://127.0.0.1:11434",
			Model:     "deepseek-r1:7b",
			TimeoutMS: 2000,
		},
		Auth: AuthConfig{
			Enabled:   false,
			JWTSecret: "",
			Issuer:    "pali",
		},
		Logging: LoggingConfig{
			DevVerbose: false,
			Progress:   true,
		},
	}
}
